layout_spectrum: 0.41926877428906606
typography_spectrum: 0.7502931795903657
color:
  brandStrength: 0.9297806806915837
  lightness: 0.9938994037048282
  saturation: 1
  rhythmicContrast: 0.5450770207515706
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: beerhouseinstitute
content: []
title: ' Beer House Photo Center'
description: A Visual Expose into Craft Beer
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2cabc945-2eec-42f4-bd4d-0d6d447a5337.jpg
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/db439641-7cb4-4af1-a956-a7b9dc27902a.jpg
purpose: []
