colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: beerhouseinstitute
layout_spectrum: 0.6519770585000515
typography_spectrum: 0.15049712406471372
color:
  brandStrength: 0.37303956924006343
  lightness: 0.8014397365041077
  saturation: 0.018549332162365317
  rhythmicContrast: 0.48639180161990225
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: article
    html: >-
      <article><h1>Clever bird! Parrot uses BEAK to open bottle of beer | Daily
      Mail Online</h1><p>Clever bird! Parrot uses BEAK to open bottle of beer
      for his owner in a cute video clip uploaded to Vine.</p><img
      src="http://i.dailymail.co.uk/i/pix/2015/11/18/12/2E8F97D600000578-0-image-a-21_1447849759232.jpg"></article>
    src: >-
      http://i.dailymail.co.uk/i/pix/2015/11/18/12/2E8F97D600000578-0-image-a-21_1447849759232.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'http://www.dailymail.co.uk'
        name: Mail Online
        favicon: 'http://www.dailymail.co.uk/favicon.ico'
        domain: www.dailymail.co.uk
      keywords:
        - mail
        - metro
        - archive
        - text-based
        - zoopla
        - screensaver
        - sitemap
        - jobsite
        - parrot
        - daily
      description: >-
        Clever bird! Parrot uses BEAK to open bottle of beer for his owner in a
        cute video clip uploaded to Vine.
      inLanguage: en
      app_links:
        - url: 'dailymail-fb://channel/video/'
          type: ios
          namespace: ai
          app_store_id: '384101264'
          app_name: MailOnline
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        http://www.dailymail.co.uk/video/news/video-1229981/Clever-bird-Parrot-uses-BEAK-open-bottle-beer.html
      title: Clever bird! Parrot uses BEAK to open bottle of beer | Daily Mail Online
      datePublished: null
    title: Clever bird! Parrot uses BEAK to open bottle of beer | Daily Mail Online
    caption: >-
      Clever bird! Parrot uses BEAK to open bottle of beer for his owner in a
      cute video clip uploaded to Vine.
    text: !<tag:yaml.org,2002:js/undefined> ''
title: The Beer House Photo Gallery
description: A Photo Expose of the World's Most Popular Beverage
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/50d186e0-78c9-4220-93e8-958b819c34a4.jpg
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/db439641-7cb4-4af1-a956-a7b9dc27902a.jpg
purpose: []
