layout_spectrum: 0.6019637527875602
typography_spectrum: 0.11417100107481722
color:
  brandStrength: 0.41008965330198405
  lightness: 0.24849531642576256
  saturation: 0.13061166928251192
  rhythmicContrast: 0.6981930745895583
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: beerhouseinstitute
content: []
title: ' Beer House Photo Center'
description: A Visual Expose into Craft Beer
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/50d186e0-78c9-4220-93e8-958b819c34a4.jpg
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/db439641-7cb4-4af1-a956-a7b9dc27902a.jpg
purpose: []
